source "https://rubygems.org"

ruby ">= 3.2"

gem "rails", "~> 7.1"
gem "puma", ">= 5.0"
gem "graphql", "~> 2.3"
gem "rack-cors"
gem "sqlite3"

group :development do
  gem "graphiql-rails"
end

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end